### ISSUE TITLE
ScalarQuadraticFunction not supported with SCIP and QCQP.

### ISSUE THREAD

**Issue by votroto** [jump-dev/PolyJuMP.jl#120]
Ehm... Hello again ^_^

## Issue 
This works:
```jl
using JuMP, PolyJuMP, SCIP

m = Model(SCIP.Optimizer)

@variable(m, x >= 0)
@variable(m, y >= 0)
@variable(m, xx)

@constraint(m, xx == x*x)
@constraint(m, x + y == 1)

@objective(m, Min, xx*x + y)

optimize!(m)
```
but changing the optimizer to 
```jl
m = Model(() -> PolyJuMP.QCQP.Optimizer(SCIP.Optimizer()))
```
fails with 
```
LoadError: MathOptInterface.UnsupportedAttribute{MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarQuadraticFunction{Float64}}}: Attribute MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarQuadraticFunction{Float64}}() is not supported by the model.
```

any ideas? Is this a SCIP issue?

## Versions

 - PolyJuMP: tested with the version from pkg, and the latest 119 patch from github master)
 - Julia: 1.10.0

Same results setting it manually, of course
```jl
aff = MOI.ScalarAffineTerm(1.0, MOI.VariableIndex(y))
qua = MOI.ScalarQuadraticTerm(1.0, MOI.VariableIndex(xx), MOI.VariableIndex(x))
sqf = MOI.ScalarQuadraticFunction([qua], [aff], 0.0)
set_objective_function(m, sqf)
```

**Comment by blegat** [comment]
Thanks for the thorough testing ^^ This is because SCIP needs to bridge quadratic objective into quadratic functions but because the bridges are applied before QCQP it decides to bridge it into polynomial function which is then transformed into QCQP by the QCQP optimizer but because there is no bridge after the QCQP optimizer, it fails
